### PR TITLE
Updated faker method for 0.1.6

### PR DESCRIPTION
**Pull request by tomoguisuru**
Resolves ```faker.random.arrayElement is not a function``` error after upgrading from 0.1.5 and using Faker 2.12.1

### CODE REVIEW

**Comment by tomoguisuru** [comment]
ignore, npm wasn't updating to the correct faker version
