### ISSUE TITLE
Uncaught TypeError: children.update is not a function

### ISSUE THREAD

**Issue by kellyselden** [samselikoff/ember-cli-mirage#964]
I'm trying to update 0.21 => 0.2.2.
https://travis-ci.org/kellyselden/ember-tree/jobs/182052440#L563
failing here: https://github.com/samselikoff/ember-cli-mirage/blob/279e25b227cab4c249e5d1831a67551cb9ea50ad/addon/orm/model.js#L275
coming from this line: https://github.com/kellyselden/ember-tree/blob/d25c7f93bb8d5b1143b3e2ed7fe0a42d00eaac86/tests/dummy/mirage/scenarios/default.js#L14

Also failing for 0.2.3 and 0.2.4. I tried stepping through the code, but it doesn't make sense to me why it's breaking.

**Comment by kategengler** [comment]
I'm seeing the same exception, unfortunately in a private app, updating from 0.21 -> 0.24

My originating line is in a test and is something like:

```js
post.update('authors', [authorA, authorB]);
```

Where the authors and post were created using `server.create`. Perhaps notable is that this is a many-many association, but it worked in 0.21.

A workaround I've found:

```js
post.update('authors', server.schema.authors.find([authorA.id, authorB.id]));
```

**Comment by kellyselden** [comment]
not really an issue anymore in 0.3.x
