### ISSUE TITLE
Model.reopen not working in ember > 3.2 with ec-mirage enabled

### ISSUE THREAD

**Issue by HenryVonfire** [samselikoff/ember-cli-mirage#1381]
I have this problem with `Model.reopen` in an `initializer` that was working in `ember 3.2.0` until I updated it to `3.4.0`. At first I thought it was something related to `ember-data` but after replicating the issue in a new project with the latest version of ember, I saw that the problem wasn't there. So researching a bit more, I discovered that by disabling `ec-mirage`, the added functions in the model were found while it kept throwing the error of `foo is not a function` when enabling it. I was on `ec-mirage: 0.4.7` when it failed and updating it to `ec-mirage: 0.4.9` didn't solve the issue.

I also tested it against `ember: 3.3.0` but the issue persists

Here's a [twiddle example](https://ember-twiddle.com/23b4477e499a2912b43956e0e1da546c?openFiles=controllers.application.js%2C) based on the template provided. Here it works because I can't use a version of ember newer than 3.2 but it can show the smallest application required to create the issue.

**Comment by abadri** [comment]
@HenryVonfire in your initializer please add `before: 'ember-cli-mirage',` https://ember-twiddle.com/a40bdca13bcee6ee4cea2aa2a28f2a34?openFiles=initializers.model-ext.js%2C

**Comment by samselikoff** [comment]
@HenryVonfire Looking into this. Definitely unexpected and you shouldn't have to specify `before` (even if it fixes it).

**Comment by samselikoff** [comment]
@HenryVonfire I'm going to close this for now because I don't believe this is specifically a Mirage bug. I think you should move your `reopen` code out of an initializer. We usually put this kind of code in `app.js`. (This is where we usually put it).

I made a reproduction of your app & initializer:

```js
export function initialize(application) {
  // console.log(application.__container__.factoryFor('model:user'));
  
  Model.reopen({
    exampleFun() {
      console.log("calling exampleFun")
    }
  })
}
```

If you uncomment the call to `factoryFor`, you'll see that the app breaks in the same way you were reporting. `factoryFor` in this case is a private API but other addons will possibly use public APIs to call `lookup` which will resolve the Model class in Ember's container, at which point this code will break.

So I think Mirage just so happens to bring one of these addons along which exposes the problem, but the fix is to move this code to `app.js`. (My understanding is not 100% clear here but I do think this code should be moved.)

Closing the issue for now, but let me know if you're still having issues or this isn't a good solution for you!

**Comment by HenryVonfire** [comment]
@samselikoff Thank you for taking the time to check this issue. I ended up taking a completely different approach without needing to reopen the Model class.
