### ISSUE TITLE
1.0.0-beta.2 Breaks Links with JSONApiSerializer

### ISSUE THREAD

**Issue by jherdman** [samselikoff/ember-cli-mirage#1637]
# Bug or question

Here's a JSON:API Serializer that works with 1.0.0-beta.1:

```javascript
import { JSONAPISerializer } from 'ember-cli-mirage';

export default JSONAPISerializer.extend({
  alwaysIncludeLinkageData: true,

  keyForAttribute(attr) {
    return attr.underscore();
  },

  keyForRelationship(modelName) {
    return modelName.underscore();
  },

  keyForModel() { return 'message'; },

  typeKeyForModel() { return 'message'; },
});
```

Upgrading to beta.2 I'm seeing the following error:

```
serializer.links is not a function
```

I'll try and whip up a repro, but it's pretty much as simple as the above right now. The boilerplate link provided is a bit dated and broken.

**Comment by samselikoff** [comment]
Believe I know the issue

**Comment by samselikoff** [comment]
Hm having trouble with the reproduction.

Moving off of Twiddle and CodeSandbox for the boilerplate as they are both unreliable.

I made a new repo and created a branch trying to reproduce your issue:

- PR: https://github.com/samselikoff/ember-cli-mirage-boilerplate/pull/1
- Branch: https://github.com/samselikoff/ember-cli-mirage-boilerplate/tree/1637/links-bug

Could you check out that branch and try to reproduce the issue?

**Comment by jherdman** [comment]
Hey Sam! I opened https://github.com/samselikoff/ember-cli-mirage-boilerplate/pull/2 that reproduces the error above. Thanks for taking the time to set up the boilerplate repo!

**Comment by samselikoff** [comment]
So... your bug turned out to reveal something of a flaw in the current API design 😄

I actually know of a quick fix to your specific issue, but the flaw it revealed is that, using a single named serializer in the `this.serialize(user, 'v2-user')` is actually insufficient.

The way serializers work is via a hierarchy. When first starting out, apps define a single `Application` serializer that is used for every model, and then as model-specific customizations are required, folks can define model-specific serializers like `/serializers/user.js`.

If a model-specific serializer is defined, Mirage will use that for that model; but serialization is a mult-model process. If there's a request to `GET /users?include=posts`, users will be serialized with `serializers/user.js`, but posts will fall back to the default `application.js`.

All that to say, the API for the `this.serialize` helper turns out to be a little ambiguous. For example, say you needed to handle the request `GET /users?include.posts.reviewers`. Post now has a reviewers relationship, but reviewers are actually users too. And say you call `this.serialize('users', 'user-v2')`. Should the reviewers be serialized using `user-v2`?

There are several places in serializer-land where we are serializing a model and need to look up its serializer (or fallback) with `this.serializerFor(model)`. So now it's clear to me that we really need more information from the initial call site as to which serializer to use for _each_ model in the graph that's getting serialized.

All that to say, `this.serialize('user', 'user-v2')` is kinda insufficient. What you really want is a _new_ serializer hierarchy, a v2 **hierarchy** rather than just a v2 user serializer. When serializing a user in v2, you really want _everything_ to be serialized with a v2 Application Serializer.

So, I think we should add a new feature to Mirage that lets users define new versions of their serializer hierarchy. It would look like this:

```
mirage
  /scenarios
  /serializers
    /versions
      /v2
        application.js
        user.js
    application.js
    user.js
    post.js
  config.js
```

Existing code would use the default hierarchy defined in the root of `mirage/serializers` as the default. But now, we'll introduce a new option to the `this.serialize` helper that let's you specify which serializer version you want to use:

```js
this.get('/v2/users/:id', function({ users }, { params: { id } }) {
  let user = users.find(id);

  return this.serialize(user, { version: 'v2' });
});
```

You can still pass in a name if you want a specific named serializer under a version:

```js
return this.serialize(user, 'user-with-linkage-data', { version: 'v2' });
```

And you could even imagine us adding a helper for specifying the serializer version or other server options when defining routes:

```js
// mirage/config.js
this.withOptions({ namespace: 'v2', serializerVersion: 'v2' }, function() {
  this.get('/users');
  this.get('/users/:id');
});
```

that way you could use shorthands but specify which serializer version you want. (Will have to think more about that specific api).

In any case, what do you think the options argument to `this.serialize`? Do you think that would be useful & clear for your use case?

**Comment by jherdman** [comment]
> I actually know of a quick fix to your specific issue ...

I'm definitely interested in this in the interim ;)

With regards to your proposal I think this is the first toe in a quagmire pool. My hunch is that the existing solution solves 99% of everyone's use case out there, so I'm a bit reluctant to change it much. That said I think clear escape valves are always a good idea.

Give your proposal, when I'm an API author who is introducing a new version, and V1 is AMS, and V2 is JSON:API, what happens if my `User` model has a many relationship that still lives as a V1 resource? Using myself as an example, I'm currently ONLY returning data linkages for these V1 resources and not `"links"`. Would I be able to specify and/or control this?

**Comment by samselikoff** [comment]
@jherdman Hey James! When you have time could you give https://github.com/samselikoff/ember-cli-mirage/pull/1672 a shot and see if it fixes your issue? It's the "quick fix" version of this.

**Comment by jherdman** [comment]
Worked like a charm!
